import test from 'node:test';
import assert from 'node:assert/strict';
import { SkillBindingRegistry, SkillRegistry, QuotaLedger, W6Error } from '../dist/index.js';
import { skillTestFixtureDigest } from '@mobile-ai-keyboard/contracts';

const owner = { user_id: 'usr_1234567890abcdef', device_id: 'dev_1234567890abcdef' };
const other = { user_id: 'usr_2234567890abcdef', device_id: 'dev_2234567890abcdef' };
const fixtureClock = () => { let value = new Date('2026-08-26T00:10:00.000Z'); return { clock: () => new Date(value), advance: (ms) => { value = new Date(value.getTime() + ms); } }; };
const definition = (name = '日程検索') => ({ schema_version: 1, name, description: '空き時間を確認します', trigger: { kind: 'phrase', value: '空き時間' }, inputs: [{ name: 'proposal', type: 'text', sources: ['selection'], required: true, max_characters: 4000 }], tools: [{ operation: 'calendar.availability.read', required_scopes: ['calendar.availability.read'], side_effect: 'none' }], risk_ceiling: 'R2', confirmation: 'policy_required', output: { type: 'insert_text', template: '候補を表示します' }, retention: 'transient_content', instruction: '予定の候補だけを整理します。', tests: [{ name: 'relative date', input_fixture: '来週火曜15時', expected: { requires_absolute_date_preview: true } }] });
const testRun = (draft, overrides = {}) => ({ test_run_id: 'strun_1234567890abcdef', draft_id: draft.draft_id, draft_revision: draft.revision, contract_digest: draft.contract_digest, results: draft.definition.tests.map((test) => ({ test_name: test.name, fixture_digest: skillTestFixtureDigest(test), actual: { ...test.expected }, user_visible_result: '候補を表示しました' })), all_pass: true, completed_at: '2026-08-26T00:10:00.000Z', ...overrides });
const binding = (version, overrides = {}) => ({ binding_id: 'bind_1234567890abcdef', user_id: owner.user_id, device_id: owner.device_id, skill_id: version.skill_id, version_id: version.version_id, skill_version: version.version, skill_digest: version.contract_digest, trigger: version.definition.trigger, accessibility_label: '空き時間を確認', accessibility_hint: '予定の候補を表示します', accessibility_order: 1, enabled: true, bound_at: '2026-08-26T00:10:00.000Z', ...overrides });
const makeReservation = (overrides = {}) => ({ reservation_id: 'qres_1234567890abcdef', user_id: owner.user_id, skill_id: 'skill_1234567890abcdef', skill_version: 1, period_start: '2026-08-26T00:00:00.000Z', request_id: 'quota-request-1', input_characters: 10, estimated_output_characters: 20, estimated_cost_micros: 100, status: 'reserved', reserved_at: '2026-08-26T00:10:00.000Z', ...overrides });
const quota = { user_id: owner.user_id, period_start: '2026-08-26T00:00:00.000Z', period_end: '2026-08-26T01:00:00.000Z', max_runs: 1, max_input_characters: 100, max_output_characters: 100, max_cost_micros: 1000 };

test('draft -> validated -> tested -> immutable private version and explicit upgrade', () => {
  const f = fixtureClock(); const registry = new SkillRegistry(f.clock); const draft = registry.createDraft(owner, definition()); assert.equal(draft.revision, 1); const validated = registry.validateDraft(draft.draft_id, owner); assert.equal(validated.status, 'validated'); const tested = registry.markTested(draft.draft_id, owner, testRun(validated)); assert.equal(tested.status, 'tested'); const first = registry.publishPrivate(draft.draft_id, owner); assert.equal(first.version, 1); assert.equal(first.visibility, 'private');
  const updatedDraft = registry.updateDraft(draft.draft_id, owner, definition('日程検索改')); const updatedValidated = registry.validateDraft(updatedDraft.draft_id, owner); registry.markTested(updatedDraft.draft_id, owner, testRun(updatedValidated)); const second = registry.publishPrivate(updatedDraft.draft_id, owner); assert.equal(second.version, 2);
  const bindings = new SkillBindingRegistry(f.clock); const installed = bindings.bind(binding(first), first, owner); assert.throws(() => bindings.upgrade(installed.binding_id, second, owner, false), (error) => error instanceof W6Error && error.code === 'BINDING_CONFLICT'); const upgraded = bindings.upgrade(installed.binding_id, second, owner, true); assert.equal(upgraded.skill_digest, second.contract_digest);
});

test('testing is bound to the exact draft revision/digest and every fixture result', () => {
  const f = fixtureClock(); const registry = new SkillRegistry(f.clock); const draft = registry.createDraft(owner, definition()); const validated = registry.validateDraft(draft.draft_id, owner);
  assert.throws(() => registry.markTested(draft.draft_id, owner, testRun(validated, { contract_digest: 'sha256:' + '0'.repeat(64) })), (error) => error instanceof W6Error && error.code === 'SKILL_TEST_STALE');
  assert.throws(() => registry.markTested(draft.draft_id, owner, testRun(validated, { results: [] })), (error) => error instanceof W6Error && error.code === 'SKILL_TEST_RESULT_INVALID');
  const validResult = testRun(validated).results[0]; assert.throws(() => registry.markTested(draft.draft_id, owner, testRun(validated, { results: [{ ...validResult, actual: { requires_absolute_date_preview: false } }] })), (error) => error instanceof W6Error && error.code === 'SKILL_TEST_RESULT_INVALID');
  assert.throws(() => registry.markTested(draft.draft_id, owner, testRun(validated, { results: [{ ...validResult, fixture_digest: 'sha256:' + '0'.repeat(64) }] })), (error) => error instanceof W6Error && error.code === 'SKILL_TEST_RESULT_INVALID');
  assert.throws(() => registry.markTested(draft.draft_id, owner, testRun(validated, { results: [validResult, validResult] })), (error) => error instanceof W6Error && error.code === 'SKILL_TEST_RESULT_INVALID');
  const staleDraft = registry.updateDraft(draft.draft_id, owner, definition('改訂Skill')); const staleValidated = registry.validateDraft(staleDraft.draft_id, owner); assert.throws(() => registry.markTested(draft.draft_id, owner, testRun(validated)), (error) => error instanceof W6Error && error.code === 'SKILL_TEST_STALE'); assert.doesNotThrow(() => registry.markTested(staleDraft.draft_id, owner, testRun(staleValidated)));
});

test('binding conflicts cover typing, accessibility, existing IDs, and cross-skill/owner upgrades', () => {
  const f = fixtureClock(); const registry = new SkillRegistry(f.clock); const d1 = registry.createDraft(owner, definition()); const d1v = registry.validateDraft(d1.draft_id, owner); registry.markTested(d1.draft_id, owner, testRun(d1v)); const v1 = registry.publishPrivate(d1.draft_id, owner); const d2 = registry.createDraft(other, definition('別Skill')); const d2v = registry.validateDraft(d2.draft_id, other); registry.markTested(d2.draft_id, other, testRun(d2v)); const otherVersion = registry.publishPrivate(d2.draft_id, other); const bindings = new SkillBindingRegistry(f.clock); const installed = bindings.bind(binding(v1), v1, owner); assert.equal(bindings.bind(binding(v1), v1, owner).binding_id, installed.binding_id); assert.throws(() => bindings.bind(binding(v1, { accessibility_hint: 'different' }), v1, owner), (error) => error instanceof W6Error && error.code === 'BINDING_CONFLICT');
  assert.throws(() => bindings.bind(binding(v1, { binding_id: 'bind_4234567890abcdef', accessibility_label: '   ' }), v1, owner), (error) => error instanceof W6Error && error.code === 'INVALID_CONTRACT');
  assert.throws(() => bindings.bind(binding(v1, { binding_id: 'bind_2234567890abcdef', trigger: { kind: 'shortcut', value: 'space' }, accessibility_order: 2 }), v1, owner), (error) => error instanceof W6Error && error.code === 'TYPING_CONFLICT');
  assert.throws(() => bindings.bind(binding(v1, { binding_id: 'bind_3234567890abcdef', accessibility_order: 1 }), v1, owner), (error) => error instanceof W6Error && error.code === 'BINDING_CONFLICT');
  assert.throws(() => bindings.upgrade(installed.binding_id, otherVersion, owner, true), (error) => error instanceof W6Error && error.code === 'BINDING_VERSION_MISMATCH');
  assert.throws(() => bindings.upgrade(installed.binding_id, v1, other, true), (error) => error instanceof W6Error && error.code === 'BINDING_CONFLICT');
});

test('private share is owner/version-bound, private-only, immutable and idempotent', () => {
  const f = fixtureClock(); const registry = new SkillRegistry(f.clock); const draft = registry.createDraft(owner, definition()); const validated = registry.validateDraft(draft.draft_id, owner); registry.markTested(draft.draft_id, owner, testRun(validated)); const version = registry.publishPrivate(draft.draft_id, owner); const value = { share_id: 'share_1234567890abcdef', skill_id: version.skill_id, version_id: version.version_id, skill_digest: version.contract_digest, owner_user_id: owner.user_id, recipient_user_ids: [other.user_id], visibility: 'private', public_publish: false, expires_at: '2026-08-26T00:30:00.000Z', created_at: '2026-08-26T00:10:00.000Z' }; assert.equal(registry.sharePrivate(value, owner.user_id).share_id, value.share_id); assert.equal(registry.sharePrivate(value, owner.user_id).share_id, value.share_id); assert.throws(() => registry.sharePrivate({ ...value, recipient_user_ids: ['usr_3234567890abcdef'] }, owner.user_id), /immutable/); assert.throws(() => registry.sharePrivate({ ...value, share_id: 'share_2234567890abcdef', public_publish: true }, owner.user_id), /contract/); assert.throws(() => registry.sharePrivate({ ...value, share_id: 'share_3234567890abcdef' }, other.user_id), /bound|owner/);
});

test('quota reservations include usage, cost, period, idempotency, commit and release', () => {
  const f = fixtureClock(); const ledger = new QuotaLedger(); const first = ledger.reserve(makeReservation(), quota, f.clock()); assert.equal(first.status, 'reserved'); assert.equal(ledger.reserve(makeReservation(), quota, f.clock()).reservation_id, first.reservation_id); assert.throws(() => ledger.reserve(makeReservation({ estimated_cost_micros: 101 }), quota, f.clock()), (error) => error instanceof W6Error && error.code === 'QUOTA_IDEMPOTENCY_CONFLICT'); assert.throws(() => ledger.reserve(makeReservation({ reservation_id: 'qres_2234567890abcdef', request_id: first.reservation_id }), quota, f.clock()), (error) => error instanceof W6Error && error.code === 'QUOTA_IDEMPOTENCY_CONFLICT'); assert.throws(() => ledger.reserve(makeReservation({ reservation_id: 'qres_2234567890abcdef', request_id: 'quota-request-2' }), quota, f.clock()), (error) => error instanceof W6Error && error.code === 'QUOTA_EXCEEDED'); assert.throws(() => ledger.commit(first.reservation_id, other.user_id), (error) => error instanceof W6Error && error.code === 'RESERVATION_OWNER_MISMATCH'); assert.equal(ledger.commit(first.reservation_id, owner.user_id).status, 'committed'); assert.throws(() => ledger.release(first.reservation_id, owner.user_id), (error) => error instanceof W6Error && error.code === 'RESERVATION_STATE_CONFLICT');
  const late = fixtureClock(); late.advance(2 * 60 * 60_000); assert.throws(() => new QuotaLedger().reserve(makeReservation({ reservation_id: 'qres_3234567890abcdef', request_id: 'quota-request-3' }), quota, late.clock()), (error) => error instanceof W6Error && error.code === 'QUOTA_EXCEEDED');
});
