import { canonicalJson, ContextualSuggestion, ModerationDecision, PublisherIdentity, PublisherVerificationDecision, PublisherVerificationEvidence, SignedSkillPackage, SkillControlAction, SkillReport, SkillRollbackRequest, SkillSafetyMetadata, SuggestionTelemetryEvent, TeamPolicyInstall, TeamPolicyPackage, TeamPolicyRevocation, TeamPolicyUpgrade, contextualSuggestionDigest, publisherIdentityDigest, safetyMetadataDigest, signedSkillPackageDigest, skillReportDigest, teamPolicyPackageDigest } from "@mobile-ai-keyboard/contracts";
import type { ContextualSuggestion as ContextualSuggestionData, ModerationDecision as ModerationDecisionData, PublisherIdentity as PublisherIdentityData, PublisherVerificationDecision as PublisherVerificationDecisionData, SignedSkillPackage as SignedSkillPackageData, SkillControlAction as SkillControlActionData, SkillReport as SkillReportData, SkillRollbackRequest as SkillRollbackRequestData, SkillSafetyMetadata as SkillSafetyMetadataData, SuggestionTelemetryEvent as SuggestionTelemetryEventData, TeamPolicyInstall as TeamPolicyInstallData, TeamPolicyPackage as TeamPolicyPackageData, TeamPolicyRevocation as TeamPolicyRevocationData, TeamPolicyUpgrade as TeamPolicyUpgradeData, UserId } from "@mobile-ai-keyboard/contracts";
import { PolicyViolation } from "./index.js";

export const W8_PROTECTED_EVIDENCE_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1_000;
export const W8_SAFETY_METADATA_MAX_AGE_MS = 30 * 24 * 60 * 60 * 1_000;
const ranks = { R0: 0, R1: 1, R2: 2, R3: 3, R4: 4, R5: 5 } as const;
const operationCatalog: Record<string, { scopes: readonly string[]; risk: keyof typeof ranks }> = {
  "calendar.availability.read": { scopes: ["calendar.availability.read"], risk: "R2" },
  "notion.pages.search": { scopes: ["notion.pages.search"], risk: "R2" },
  "maps.places.search": { scopes: ["maps.places.search"], risk: "R2" },
  "calendar.event.create_private": { scopes: ["calendar.events.create_private"], risk: "R3" }
};
const r4Operations = new Set(["email.send", "message.send", "publish.content", "calendar.event.invite"]);
const exactArray = (left: readonly string[], right: readonly string[]): boolean => left.length === right.length && left.every((value, index) => value === right[index]);

export function validatePublisherIdentity(value: unknown): PublisherIdentityData {
  const parsed = PublisherIdentity.safeParse(value); if (!parsed.success) throw new PolicyViolation("Publisher identity contract is invalid", { code: "INVALID_PUBLISHER_IDENTITY" });
  const { identity_digest: _digest, ...unsigned } = parsed.data; if (publisherIdentityDigest(unsigned) !== parsed.data.identity_digest) throw new PolicyViolation("Publisher identity digest mismatch", { code: "PUBLISHER_IDENTITY_DIGEST_MISMATCH" }); return parsed.data;
}
export function validateSignedSkillPackage(value: unknown, publisher?: PublisherIdentityData): SignedSkillPackageData {
  const parsed = SignedSkillPackage.safeParse(value); if (!parsed.success) throw new PolicyViolation("Signed Skill package contract is invalid", { code: "INVALID_SIGNED_PACKAGE" });
  const { package_digest: _digest, signature: _signature, ...unsigned } = parsed.data; if (signedSkillPackageDigest(unsigned) !== parsed.data.package_digest) throw new PolicyViolation("Signed Skill package digest mismatch", { code: "SIGNED_PACKAGE_DIGEST_MISMATCH" }); if (publisher && (parsed.data.publisher_id !== publisher.publisher_id || parsed.data.signing_key_id !== publisher.signing_key_id)) throw new PolicyViolation("Signed package is bound to another publisher key", { code: "PUBLISHER_BINDING_MISMATCH" }); return parsed.data;
}
export function evaluatePublisherEvidence(value: unknown, packageValue: unknown, publisherValue: unknown, trustedEvidenceIds: ReadonlySet<string> = new Set(), now = new Date()): PublisherVerificationDecisionData {
  const publisher = validatePublisherIdentity(publisherValue); const packageValueParsed = validateSignedSkillPackage(packageValue, publisher); const evidence = PublisherVerificationEvidence.safeParse(value); if (!evidence.success) throw new PolicyViolation("Publisher evidence contract is invalid", { code: "INVALID_PUBLISHER_EVIDENCE" });
  if (evidence.data.publisher_id !== publisher.publisher_id || evidence.data.package_id !== packageValueParsed.package_id || evidence.data.package_digest !== packageValueParsed.package_digest || evidence.data.identity_digest !== publisher.identity_digest || evidence.data.signing_key_id !== publisher.signing_key_id) throw new PolicyViolation("Publisher evidence is not bound to the exact package/key", { code: "PUBLISHER_BINDING_MISMATCH" });
  const age = now.getTime() - Date.parse(evidence.data.observed_at); let status: "verified" | "not_proven" = "not_proven"; let reason: PublisherVerificationDecisionData["reason"] = evidence.data.verifier_kind === "self_attested" ? "self_attested" : evidence.data.verifier_kind === "fixture" ? "fixture" : "binding_mismatch";
  if (evidence.data.verification_status === "verified" && evidence.data.verifier_kind === "protected_verifier" && evidence.data.verifier_id !== undefined && trustedEvidenceIds.has(evidence.data.evidence_id) && age >= 0 && age <= W8_PROTECTED_EVIDENCE_MAX_AGE_MS) { status = "verified"; reason = "trusted_protected_verifier"; } else if (age < 0) reason = "future"; else if (age > W8_PROTECTED_EVIDENCE_MAX_AGE_MS) reason = "stale";
  const validUntil = new Date(Date.parse(evidence.data.observed_at) + W8_PROTECTED_EVIDENCE_MAX_AGE_MS).toISOString(); return PublisherVerificationDecision.parse({ publisher_id: publisher.publisher_id, package_id: packageValueParsed.package_id, package_digest: packageValueParsed.package_digest, status, reason, evaluated_at: now.toISOString(), valid_until: validUntil });
}

export function validateTeamPolicyPackage(value: unknown): TeamPolicyPackageData {
  const parsed = TeamPolicyPackage.safeParse(value); if (!parsed.success) throw new PolicyViolation("Team policy package contract is invalid", { code: "INVALID_TEAM_POLICY" });
  const { package_digest: _digest, ...unsigned } = parsed.data; if (teamPolicyPackageDigest(unsigned) !== parsed.data.package_digest) throw new PolicyViolation("Team policy package digest mismatch", { code: "TEAM_POLICY_DIGEST_MISMATCH" });
  for (const tool of parsed.data.allowed_tools) { const catalog = operationCatalog[tool.operation]; if (r4Operations.has(tool.operation)) throw new PolicyViolation("R4 connector operation is prohibited without separate external security evidence", { code: "R4_CONNECTOR_NOT_PROVEN" }); if (!catalog || !exactArray(tool.required_scopes, catalog.scopes)) throw new PolicyViolation("Team policy tool or scope is outside the exact allowlist", { code: "TEAM_TOOL_SCOPE_MISMATCH" }); if (ranks[catalog.risk] > ranks[parsed.data.risk_ceiling]) throw new PolicyViolation("Team policy risk ceiling is below an allowed operation", { code: "TEAM_RISK_CEILING_MISMATCH" }); }
  if (parsed.data.risk_ceiling === "R4" || parsed.data.risk_ceiling === "R5") throw new PolicyViolation("R4/R5 team policy is not proven and remains disabled", { code: "R4_CONNECTOR_NOT_PROVEN" }); if (parsed.data.risk_ceiling !== "R0" && parsed.data.risk_ceiling !== "R1" && parsed.data.confirmation !== "policy_required") throw new PolicyViolation("Team policy requires explicit confirmation for external operations", { code: "TEAM_CONFIRMATION_REQUIRED" }); return parsed.data;
}
export function validateTeamPolicyInstall(value: unknown, policyValue: unknown, owner: UserId): TeamPolicyInstallData {
  const policy = validateTeamPolicyPackage(policyValue); const parsed = TeamPolicyInstall.safeParse(value); if (!parsed.success) throw new PolicyViolation("Team policy install contract is invalid", { code: "INVALID_TEAM_INSTALL" }); if (parsed.data.owner_user_id !== owner || parsed.data.team_id !== policy.team_id || parsed.data.policy_id !== policy.policy_id || parsed.data.version !== policy.version || parsed.data.policy_epoch !== policy.policy_epoch || parsed.data.package_digest !== policy.package_digest) throw new PolicyViolation("Team policy install is not bound to the exact owner/team/version", { code: "TEAM_POLICY_BINDING_MISMATCH" }); return parsed.data;
}
export function validateTeamPolicyUpgrade(value: unknown, current: TeamPolicyInstallData, nextValue: unknown, owner: UserId): TeamPolicyUpgradeData {
  const next = validateTeamPolicyPackage(nextValue); const parsed = TeamPolicyUpgrade.safeParse(value); if (!parsed.success) throw new PolicyViolation("Team policy upgrade contract is invalid", { code: "INVALID_TEAM_UPGRADE" }); if (parsed.data.owner_user_id !== owner || parsed.data.team_id !== current.team_id || parsed.data.current_policy_id !== current.policy_id || parsed.data.current_version !== current.version || parsed.data.current_package_digest !== current.package_digest || parsed.data.next_policy_id !== next.policy_id || parsed.data.next_policy_id !== current.policy_id || parsed.data.next_version !== next.version || parsed.data.next_package_digest !== next.package_digest || parsed.data.policy_epoch !== next.policy_epoch || next.version <= current.version || next.policy_epoch < current.policy_epoch) throw new PolicyViolation("Team policy upgrade is stale, cross-owner, unrelated-policy, or not monotonic", { code: "TEAM_POLICY_UPGRADE_MISMATCH" }); return parsed.data;
}

export function validateTeamPolicyRevocation(value: unknown, policyValue: unknown, owner: UserId, previous?: TeamPolicyRevocationData): TeamPolicyRevocationData {
  const policy = validateTeamPolicyPackage(policyValue); const parsed = TeamPolicyRevocation.safeParse(value); if (!parsed.success) throw new PolicyViolation("Team policy revocation contract is invalid", { code: "INVALID_TEAM_REVOCATION" }); const same = previous !== undefined && canonicalJson(previous) === canonicalJson(parsed.data); if (parsed.data.owner_user_id !== owner || parsed.data.team_id !== policy.team_id || parsed.data.policy_id !== policy.policy_id || parsed.data.version !== policy.version || parsed.data.policy_epoch !== policy.policy_epoch || parsed.data.package_digest !== policy.package_digest || (previous === undefined ? parsed.data.revision !== 1 : !same && parsed.data.revision !== previous.revision + 1)) throw new PolicyViolation("Team policy revocation is not exact, owner-bound, or monotonic", { code: "TEAM_POLICY_REVOCATION_MISMATCH" }); return parsed.data;
}

export function validateContextualSuggestion(value: unknown, now = new Date()): ContextualSuggestionData { const parsed = ContextualSuggestion.safeParse(value); if (!parsed.success) throw new PolicyViolation("Contextual suggestion contract is invalid", { code: "INVALID_SUGGESTION" }); const { suggestion_digest: _digest, ...unsigned } = parsed.data; if (contextualSuggestionDigest(unsigned) !== parsed.data.suggestion_digest) throw new PolicyViolation("Contextual suggestion digest mismatch", { code: "SUGGESTION_DIGEST_MISMATCH" }); if (Date.parse(parsed.data.generated_at) > now.getTime()) throw new PolicyViolation("Contextual suggestion is future-dated", { code: "SUGGESTION_FUTURE" }); if (Date.parse(parsed.data.expires_at) <= now.getTime()) throw new PolicyViolation("Contextual suggestion is expired", { code: "SUGGESTION_EXPIRED" }); return parsed.data; }
export function validateSuggestionTelemetry(value: unknown, owner: UserId): SuggestionTelemetryEventData { const parsed = SuggestionTelemetryEvent.safeParse(value); if (!parsed.success || parsed.data.owner_user_id !== owner) throw new PolicyViolation("Suggestion telemetry is invalid or cross-owner", { code: "INVALID_SUGGESTION_TELEMETRY" }); return parsed.data; }

export function validateSafetyMetadata(value: unknown, now = new Date(), trustedMetadataIds: ReadonlySet<string> = new Set()): SkillSafetyMetadataData { const parsed = SkillSafetyMetadata.safeParse(value); if (!parsed.success) throw new PolicyViolation("Skill safety metadata contract is invalid", { code: "INVALID_SAFETY_METADATA" }); const { metadata_digest: _digest, ...unsigned } = parsed.data; if (safetyMetadataDigest(unsigned) !== parsed.data.metadata_digest) throw new PolicyViolation("Safety metadata digest mismatch", { code: "SAFETY_METADATA_DIGEST_MISMATCH" }); const expectedConfidence = parsed.data.completion_denominator >= 100 ? "high" : parsed.data.completion_denominator >= 30 ? "medium" : "low"; if (parsed.data.confidence !== expectedConfidence) throw new PolicyViolation("Completion confidence does not match minimum sample policy", { code: "SAFETY_CONFIDENCE_MISMATCH" }); const reviewedAt = Date.parse(parsed.data.last_reviewed_at); if (reviewedAt > now.getTime() || now.getTime() - reviewedAt > W8_SAFETY_METADATA_MAX_AGE_MS) throw new PolicyViolation("Safety metadata review is outside the bounded window", { code: "SAFETY_METADATA_STALE" }); if (parsed.data.provenance === "protected_verified" && (parsed.data.publisher_verification !== "verified" || !trustedMetadataIds.has(parsed.data.metadata_id) || parsed.data.completion_denominator < 100)) throw new PolicyViolation("Protected safety metadata requires trusted publisher evidence and minimum sample", { code: "SAFETY_METADATA_NOT_PROVEN" }); if (parsed.data.provenance !== "protected_verified" && parsed.data.publisher_verification !== "not_proven") throw new PolicyViolation("Unproven metadata cannot claim a verified publisher", { code: "SAFETY_METADATA_NOT_PROVEN" }); return parsed.data; }
export function validateSkillReport(value: unknown): SkillReportData { const parsed = SkillReport.safeParse(value); if (!parsed.success) throw new PolicyViolation("Skill report contract is invalid", { code: "INVALID_SKILL_REPORT" }); const { report_digest: _digest, ...unsigned } = parsed.data; if (skillReportDigest(unsigned) !== parsed.data.report_digest) throw new PolicyViolation("Skill report digest mismatch", { code: "SKILL_REPORT_DIGEST_MISMATCH" }); return parsed.data; }
export function validateModerationDecision(value: unknown, packageValue: SignedSkillPackageData, reports: readonly SkillReportData[], trustedModeratorIds: ReadonlySet<string> = new Set()): ModerationDecisionData { const packageParsed = validateSignedSkillPackage(packageValue); const parsed = ModerationDecision.safeParse(value); if (!parsed.success) throw new PolicyViolation("Moderation decision contract is invalid", { code: "INVALID_MODERATION" }); const matchingReports = reports.map((report) => validateSkillReport(report)); if (parsed.data.skill_id !== packageParsed.skill_id || parsed.data.version_id !== packageParsed.version_id || parsed.data.package_digest !== packageParsed.package_digest || new Set(parsed.data.report_ids).size !== parsed.data.report_ids.length || parsed.data.report_ids.some((id) => !matchingReports.some((report) => report.report_id === id && report.skill_id === packageParsed.skill_id && report.version_id === packageParsed.version_id && report.package_digest === packageParsed.package_digest)) || (parsed.data.status === "approved" && (parsed.data.moderator_kind !== "protected_moderator" || parsed.data.verifier_id === undefined || !trustedModeratorIds.has(parsed.data.verifier_id)))) throw new PolicyViolation("Moderation decision is not exact or trusted", { code: "MODERATION_NOT_PROVEN" }); return parsed.data; }
export function validateSkillControlAction(value: unknown, previous: SkillControlActionData | undefined, packageValue: SignedSkillPackageData, owner: UserId, policyEpoch: number): SkillControlActionData { const packageParsed = validateSignedSkillPackage(packageValue); const parsed = SkillControlAction.safeParse(value); if (!parsed.success) throw new PolicyViolation("Skill control action contract is invalid", { code: "INVALID_SKILL_CONTROL" }); const previousParsed = previous === undefined ? undefined : SkillControlAction.safeParse(previous); const previousValidated = previousParsed?.success ? previousParsed.data : undefined; if (previous !== undefined && previousValidated === undefined) throw new PolicyViolation("Previous skill control action is invalid", { code: "SKILL_CONTROL_CONFLICT" }); const sameAsPrevious = previousValidated !== undefined && canonicalJson(previousValidated) === canonicalJson(parsed.data); if (parsed.data.owner_user_id !== owner || parsed.data.policy_epoch !== policyEpoch || parsed.data.skill_id !== packageParsed.skill_id || parsed.data.version_id !== packageParsed.version_id || parsed.data.package_digest !== packageParsed.package_digest || (previousValidated === undefined ? parsed.data.revision !== 1 : (!sameAsPrevious && (parsed.data.revision !== previousValidated.revision + 1 || previousValidated.skill_id !== parsed.data.skill_id || previousValidated.version_id !== parsed.data.version_id || previousValidated.package_digest !== parsed.data.package_digest || previousValidated.owner_user_id !== parsed.data.owner_user_id || previousValidated.policy_epoch !== parsed.data.policy_epoch)))) throw new PolicyViolation("Skill control action is stale, cross-owner, or cross-package", { code: "SKILL_CONTROL_CONFLICT" }); return parsed.data; }
export function validateSkillRollback(value: unknown, current: { skill_id: string; version: number; package_digest: string; publisher_id: string; owner_user_id: UserId }, targetPackage: SignedSkillPackageData, owner: UserId, expectedPolicyEpoch: number): SkillRollbackRequestData { const parsed = SkillRollbackRequest.safeParse(value); if (!parsed.success) throw new PolicyViolation("Skill rollback contract is invalid", { code: "INVALID_SKILL_ROLLBACK" }); if (parsed.data.owner_user_id !== owner || parsed.data.skill_id !== current.skill_id || parsed.data.from_version !== current.version || parsed.data.from_package_digest !== current.package_digest || parsed.data.target_version !== targetPackage.skill_version || parsed.data.target_package_digest !== targetPackage.package_digest || parsed.data.publisher_id !== targetPackage.publisher_id || parsed.data.publisher_id !== current.publisher_id || parsed.data.policy_epoch !== expectedPolicyEpoch) throw new PolicyViolation("Skill rollback is not bound to the exact current/target versions or expected epoch", { code: "SKILL_ROLLBACK_MISMATCH" }); return parsed.data; }
