import { canonicalJson, ContextualSuggestion, ModerationDecision, PublisherIdentity, PublisherVerificationDecision, SignedSkillPackage, SkillControlAction, SkillReport, SuggestionTelemetryEvent, TeamPolicyInstall, TeamPolicyRevocation, UserId as UserIdSchema, type ContextualSuggestion as ContextualSuggestionData, type ModerationDecision as ModerationDecisionData, type PublisherVerificationDecision as PublisherVerificationDecisionData, type SignedSkillPackage as SignedSkillPackageData, type SkillControlAction as SkillControlActionData, type SkillReport as SkillReportData, type SuggestionTelemetryEvent as SuggestionTelemetryEventData, type TeamPolicyInstall as TeamPolicyInstallData, type TeamPolicyRevocation as TeamPolicyRevocationData, type UserId } from "@mobile-ai-keyboard/contracts";
import { evaluatePublisherEvidence, validateContextualSuggestion, validateModerationDecision, validatePublisherIdentity, validateSignedSkillPackage, validateSkillControlAction, validateSkillReport, validateSkillRollback, validateTeamPolicyInstall, validateTeamPolicyPackage, validateTeamPolicyRevocation, validateTeamPolicyUpgrade, validateSafetyMetadata, validateSuggestionTelemetry } from "@mobile-ai-keyboard/policy";

export type W8ErrorCode = "INVALID_CONTRACT" | "PUBLISHER_NOT_PROVEN" | "PUBLISHER_CONFLICT" | "TEAM_POLICY_CONFLICT" | "TEAM_POLICY_UPGRADE_MISMATCH" | "SUGGESTION_NOT_EXECUTABLE" | "SUGGESTION_CONFLICT" | "SAFETY_NOT_PROVEN" | "MODERATION_NOT_PROVEN" | "CONTROL_CONFLICT" | "ROLLBACK_CONFLICT" | "REPORT_CONFLICT";
export class W8Error extends Error { constructor(readonly code: W8ErrorCode, message: string) { super(message); this.name = "W8Error"; } }
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const policyError = (error: unknown, fallback: W8ErrorCode = "INVALID_CONTRACT"): W8Error => { const code = error instanceof Error && "details" in error ? String((error as Error & { details?: { code?: string } }).details?.code ?? "") : ""; const mapping: Record<string, W8ErrorCode> = { PUBLISHER_BINDING_MISMATCH: "PUBLISHER_CONFLICT", SIGNED_PACKAGE_DIGEST_MISMATCH: "PUBLISHER_CONFLICT", PUBLISHER_IDENTITY_DIGEST_MISMATCH: "PUBLISHER_CONFLICT", TEAM_POLICY_DIGEST_MISMATCH: "TEAM_POLICY_CONFLICT", TEAM_POLICY_BINDING_MISMATCH: "TEAM_POLICY_CONFLICT", TEAM_POLICY_UPGRADE_MISMATCH: "TEAM_POLICY_UPGRADE_MISMATCH", INVALID_TEAM_REVOCATION: "TEAM_POLICY_CONFLICT", TEAM_POLICY_REVOCATION_MISMATCH: "TEAM_POLICY_CONFLICT", SUGGESTION_DIGEST_MISMATCH: "SUGGESTION_CONFLICT", INVALID_SUGGESTION_TELEMETRY: "SUGGESTION_CONFLICT", SAFETY_METADATA_NOT_PROVEN: "SAFETY_NOT_PROVEN", MODERATION_NOT_PROVEN: "MODERATION_NOT_PROVEN", SKILL_CONTROL_CONFLICT: "CONTROL_CONFLICT", SKILL_ROLLBACK_MISMATCH: "ROLLBACK_CONFLICT", INVALID_SKILL_REPORT: "REPORT_CONFLICT" }; return new W8Error(mapping[code] ?? fallback, error instanceof Error ? error.message : "W8 policy rejected the request"); };
const call = <T>(operation: () => T): T => { try { return operation(); } catch (error) { if (error instanceof W8Error) throw error; throw policyError(error); } };

export class PublisherRegistry {
  private readonly publishers = new Map<string, ReturnType<typeof PublisherIdentity.parse>>();
  private readonly packages = new Map<string, SignedSkillPackageData>();
  private readonly decisions = new Map<string, PublisherVerificationDecisionData>();
  registerPublisher(value: unknown) { const publisher = call(() => validatePublisherIdentity(value)); const existing = this.publishers.get(publisher.publisher_id); if (existing && canonicalJson(existing) !== canonicalJson(publisher)) throw new W8Error("PUBLISHER_CONFLICT", "Publisher identity is immutable"); this.publishers.set(publisher.publisher_id, clone(publisher)); return clone(publisher); }
  registerPackage(value: unknown) { const packageValue = call(() => validateSignedSkillPackage(value)); const publisher = this.publishers.get(packageValue.publisher_id); if (!publisher) throw new W8Error("PUBLISHER_CONFLICT", "Publisher identity is not registered"); call(() => validateSignedSkillPackage(packageValue, publisher)); const existing = this.packages.get(packageValue.package_id); if (existing && canonicalJson(existing) !== canonicalJson(packageValue)) throw new W8Error("PUBLISHER_CONFLICT", "Signed package ID is immutable"); this.packages.set(packageValue.package_id, clone(packageValue)); return clone(packageValue); }
  verify(packageId: string, evidence: unknown, trustedEvidenceIds: ReadonlySet<string> = new Set(), now = new Date()): PublisherVerificationDecisionData { const packageValue = this.packages.get(packageId); if (!packageValue) throw new W8Error("PUBLISHER_CONFLICT", "Signed package was not found"); const publisher = this.publishers.get(packageValue.publisher_id); if (!publisher) throw new W8Error("PUBLISHER_CONFLICT", "Publisher identity was not found"); const decision = call(() => evaluatePublisherEvidence(evidence, packageValue, publisher, trustedEvidenceIds, now)); this.decisions.set(packageId, clone(decision)); return clone(decision); }
  assertProduction(packageId: string, now = new Date()): SignedSkillPackageData { const packageValue = this.packages.get(packageId); const decision = this.decisions.get(packageId); if (!packageValue || !decision || decision.status !== "verified" || Date.parse(decision.valid_until) <= now.getTime()) throw new W8Error("PUBLISHER_NOT_PROVEN", "Signed package has no current trusted protected verification"); return clone(packageValue); }
}

export class TeamPolicyRegistry {
  private readonly installs = new Map<string, TeamPolicyInstallData>();
  private readonly requests = new Map<string, { request: string; install_id: string; install: TeamPolicyInstallData }>();
  private readonly revocationsByDigest = new Map<string, TeamPolicyRevocationData>();
  private readonly revocationsById = new Map<string, TeamPolicyRevocationData>();
  install(value: unknown, policyValue: unknown, owner: UserId): TeamPolicyInstallData { const policy = call(() => validateTeamPolicyPackage(policyValue)); if (this.revocationsByDigest.has(policy.package_digest)) throw new W8Error("TEAM_POLICY_CONFLICT", "Revoked team policy cannot be installed"); const install = call(() => validateTeamPolicyInstall(value, policy, owner)); const existing = this.installs.get(install.install_id); if (existing) { if (canonicalJson(existing) !== canonicalJson(install)) throw new W8Error("TEAM_POLICY_CONFLICT", "Team policy install ID was reused with different payload"); return clone(existing); } this.installs.set(install.install_id, clone(install)); return clone(install); }
  revoke(value: unknown, policyValue: unknown, owner: UserId): TeamPolicyRevocationData { const policy = call(() => validateTeamPolicyPackage(policyValue)); const previous = this.revocationsByDigest.get(policy.package_digest); const revocation = call(() => validateTeamPolicyRevocation(value, policy, owner, previous)); const existingId = this.revocationsById.get(revocation.revocation_id); if (existingId && canonicalJson(existingId) !== canonicalJson(revocation)) throw new W8Error("TEAM_POLICY_CONFLICT", "Revocation ID was reused with different payload"); this.revocationsByDigest.set(revocation.package_digest, clone(revocation)); this.revocationsById.set(revocation.revocation_id, clone(revocation)); return clone(revocation); }
  upgrade(installId: string, request: unknown, nextPolicyValue: unknown, owner: UserId): TeamPolicyInstallData { const current = this.installs.get(installId); if (!current) throw new W8Error("TEAM_POLICY_CONFLICT", "Team policy installation was not found"); const next = call(() => validateTeamPolicyPackage(nextPolicyValue)); if (this.revocationsByDigest.has(next.package_digest)) throw new W8Error("TEAM_POLICY_CONFLICT", "Revoked team policy cannot become an upgrade target"); const requestId = String((request as { request_id?: string })?.request_id); const requestCanonical = canonicalJson(request); const existingRequest = this.requests.get(requestId); if (existingRequest) { if (existingRequest.request !== requestCanonical || existingRequest.install_id !== installId) throw new W8Error("TEAM_POLICY_CONFLICT", "Upgrade request ID was reused with a different payload or installation"); return clone(existingRequest.install); } const parsed = call(() => validateTeamPolicyUpgrade(request, current, next, owner)); const updated = TeamPolicyInstall.parse({ ...current, policy_id: parsed.next_policy_id, version: parsed.next_version, policy_epoch: parsed.policy_epoch, package_digest: parsed.next_package_digest, installed_at: parsed.requested_at }); this.installs.set(installId, clone(updated)); this.requests.set(parsed.request_id, { request: requestCanonical, install_id: installId, install: clone(updated) }); return clone(updated); }
  get(installId: string): TeamPolicyInstallData { const install = this.installs.get(installId); if (!install) throw new W8Error("TEAM_POLICY_CONFLICT", "Team policy installation was not found"); return clone(install); }
}

export class ContextualSuggestionRuntime {
  private readonly suggestions = new Map<string, ContextualSuggestionData>();
  private readonly events: SuggestionTelemetryEventData[] = [];
  private readonly eventsById = new Map<string, SuggestionTelemetryEventData>();
  create(value: unknown, now = new Date()): ContextualSuggestionData { const suggestion = call(() => validateContextualSuggestion(value, now)); const existing = this.suggestions.get(suggestion.suggestion_id); if (existing && canonicalJson(existing) !== canonicalJson(suggestion)) throw new W8Error("SUGGESTION_CONFLICT", "Suggestion ID is immutable"); this.suggestions.set(suggestion.suggestion_id, clone(suggestion)); return clone(suggestion); }
  execute(_suggestionId: string): never { throw new W8Error("SUGGESTION_NOT_EXECUTABLE", "Contextual suggestions are local hints and require explicit user action"); }
  record(value: unknown, owner: UserId): SuggestionTelemetryEventData { const event = call(() => validateSuggestionTelemetry(value, owner)); const suggestion = this.suggestions.get(event.suggestion_id); if (!suggestion || suggestion.owner_user_id !== event.owner_user_id || suggestion.device_id !== event.device_id) throw new W8Error("SUGGESTION_CONFLICT", "Suggestion telemetry is unknown or cross-device"); const existingById = this.eventsById.get(event.event_id); if (existingById) { if (canonicalJson(existingById) !== canonicalJson(event)) throw new W8Error("SUGGESTION_CONFLICT", "Suggestion event ID is immutable"); return clone(existingById); } const history = this.events.filter((item) => item.suggestion_id === event.suggestion_id).sort((left, right) => Date.parse(left.occurred_at) - Date.parse(right.occurred_at)); const last = history.at(-1); const terminalEvents = new Set(["accepted", "dismissed", "expired"]); if (Date.parse(event.occurred_at) < Date.parse(suggestion.generated_at) || Date.parse(event.occurred_at) > Date.parse(suggestion.expires_at) || (history.length === 0 && event.event !== "shown") || (last !== undefined && Date.parse(event.occurred_at) < Date.parse(last.occurred_at)) || (history.some((item) => item.event === "shown") && event.event === "shown") || (history.some((item) => terminalEvents.has(item.event)) && terminalEvents.has(event.event))) throw new W8Error("SUGGESTION_CONFLICT", "Suggestion telemetry chronology or lifecycle is invalid"); this.eventsById.set(event.event_id, clone(event)); this.events.push(clone(event)); return clone(event); }
  telemetry(): readonly SuggestionTelemetryEventData[] { return this.events.map(clone); }
}

export class SkillGovernanceRegistry {
  private readonly reports = new Map<string, SkillReportData>();
  private readonly controls = new Map<string, SkillControlActionData>();
  private readonly moderation = new Map<string, ModerationDecisionData>();
  private readonly moderationById = new Map<string, ModerationDecisionData>();
  private readonly current = new Map<string, { package: SignedSkillPackageData; owner: UserId; policyEpoch: number }>();
  private readonly rollbacks = new Map<string, { request: string; package: SignedSkillPackageData }>();
  constructor(private readonly trustedModeratorIds: ReadonlySet<string> = new Set()) {}
  report(value: unknown): SkillReportData { const report = call(() => validateSkillReport(value)); const existing = this.reports.get(report.report_id); if (existing && canonicalJson(existing) !== canonicalJson(report)) throw new W8Error("REPORT_CONFLICT", "Report ID is immutable"); this.reports.set(report.report_id, clone(report)); return clone(report); }
  moderate(value: unknown, packageValue: SignedSkillPackageData): ModerationDecisionData { const packageValidated = call(() => validateSignedSkillPackage(packageValue)); const parsedIds = ModerationDecision.safeParse(value); if (!parsedIds.success) throw new W8Error("MODERATION_NOT_PROVEN", "Moderation decision is invalid"); const decision = call(() => validateModerationDecision(value, packageValidated, [...this.reports.values()], this.trustedModeratorIds)); const byId = this.moderationById.get(decision.moderation_id); if (byId && canonicalJson(byId) !== canonicalJson(decision)) throw new W8Error("MODERATION_NOT_PROVEN", "Moderation ID is immutable"); const existing = this.moderation.get(decision.package_digest); if (existing) { if (canonicalJson(existing) === canonicalJson(decision)) return clone(existing); if (decision.revision !== existing.revision + 1) throw new W8Error("MODERATION_NOT_PROVEN", "Moderation revision is stale"); } this.moderation.set(decision.package_digest, clone(decision)); this.moderationById.set(decision.moderation_id, clone(decision)); return clone(decision); }
  control(value: unknown, packageValue: SignedSkillPackageData, owner: UserId, policyEpoch: number): SkillControlActionData { const packageValidated = call(() => validateSignedSkillPackage(packageValue)); const parsed = SkillControlAction.safeParse(value); const key = parsed.success ? parsed.data.skill_id : packageValidated.skill_id; const previous = this.controls.get(key); const accepted = call(() => validateSkillControlAction(value, previous, packageValidated, owner, policyEpoch)); if (previous && canonicalJson(previous) === canonicalJson(accepted)) return clone(previous); this.controls.set(key, clone(accepted)); return clone(accepted); }
  activateCurrent(value: SignedSkillPackageData, owner: UserId, policyEpoch: number): SignedSkillPackageData { const packageValue = call(() => validateSignedSkillPackage(value)); const validOwner = call(() => UserIdSchema.parse(owner)); if (!Number.isInteger(policyEpoch) || policyEpoch <= 0) throw new W8Error("ROLLBACK_CONFLICT", "Current package activation requires a positive policy epoch"); const existing = this.current.get(packageValue.skill_id); if (existing && (canonicalJson(existing.package) !== canonicalJson(packageValue) || existing.owner !== validOwner || existing.policyEpoch !== policyEpoch)) throw new W8Error("ROLLBACK_CONFLICT", "Current package activation is immutable"); if (!existing) this.current.set(packageValue.skill_id, { package: clone(packageValue), owner: validOwner, policyEpoch }); return clone(packageValue); }
  rollback(value: unknown, currentPackage: SignedSkillPackageData, targetPackage: SignedSkillPackageData, owner: UserId, expectedPolicyEpoch: number): SignedSkillPackageData { const current = call(() => validateSignedSkillPackage(currentPackage)); const target = call(() => validateSignedSkillPackage(targetPackage)); const active = this.current.get(current.skill_id); if (!active || canonicalJson(active.package) !== canonicalJson(current) || active.owner !== owner || active.policyEpoch !== expectedPolicyEpoch) throw new W8Error("ROLLBACK_CONFLICT", "Rollback current package is not the registered active package"); const request = call(() => validateSkillRollback(value, { skill_id: current.skill_id, version: current.skill_version, package_digest: current.package_digest, publisher_id: current.publisher_id, owner_user_id: owner }, target, owner, expectedPolicyEpoch)); if (target.skill_id !== current.skill_id) throw new W8Error("ROLLBACK_CONFLICT", "Rollback target skill is not exact"); const requestId = request.rollback_id; const requestCanonical = canonicalJson(request); const existingRequest = this.rollbacks.get(requestId); if (existingRequest) { if (existingRequest.request !== requestCanonical) throw new W8Error("ROLLBACK_CONFLICT", "Rollback request ID was reused with different payload"); return clone(existingRequest.package); } this.current.set(request.skill_id, { package: clone(target), owner, policyEpoch: expectedPolicyEpoch }); this.rollbacks.set(request.rollback_id, { request: requestCanonical, package: clone(target) }); return clone(target); }
}
