import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildFixture, checkFixture } from '../generate-shortcut-vectors.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

test('checked-in shortcut vectors are generated by the TypeScript authority', () => {
  const expected = `${JSON.stringify(buildFixture(), null, 2)}\n`;
  assert.equal(fs.readFileSync(path.join(root, 'fixtures/shortcut-golden-vectors.json'), 'utf8'), expected);
  assert.deepEqual(checkFixture(JSON.parse(expected)), []);
});

test('vector checker rejects fixture tampering and native proof overclaim', () => {
  const fixture = buildFixture();
  const digestTampered = structuredClone(fixture);
  digestTampered.vectors[0].input.content_digest = `sha256:${'f'.repeat(64)}`;
  assert.match(checkFixture(digestTampered).join('\n'), /digest mismatch/);

  const claimedNative = structuredClone(fixture);
  claimedNative.native_consumption_status = 'passed';
  assert.match(checkFixture(claimedNative).join('\n'), /native consumption/);

  const claimedValid = structuredClone(fixture);
  claimedValid.vectors[3].expected.contract_valid = true;
  assert.match(checkFixture(claimedValid).join('\n'), /expected contract_valid=true/);

  const claimedRejection = structuredClone(fixture);
  claimedRejection.vectors[1].expected.rejection = 'digest';
  assert.match(checkFixture(claimedRejection).join('\n'), /expected rejection=digest, got schema/);
});
