import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildFixture, checkFixture } from '../generate-shortcut-vectors.mjs';
import { inspectNativeConsumers, nativeConsumerFailures, NATIVE_CONSUMER_MARKER } from '../check-native-shortcut-consumers.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

test('checked-in shortcut vectors are generated by the TypeScript authority', () => {
  const expected = `${JSON.stringify(buildFixture(), null, 2)}\n`;
  assert.equal(fs.readFileSync(path.join(root, 'fixtures/shortcut-golden-vectors.json'), 'utf8'), expected);
  assert.deepEqual(checkFixture(JSON.parse(expected)), []);
});

test('vector checker rejects fixture tampering and native proof overclaim', () => {
  const fixture = buildFixture();
  const digestTampered = structuredClone(fixture);
  digestTampered.vectors[0].input.content_digest = `sha256:${'f'.repeat(64)}`;
  assert.match(checkFixture(digestTampered).join('\n'), /digest mismatch/);

  const claimedNative = structuredClone(fixture);
  claimedNative.native_consumption_status = 'passed';
  assert.match(checkFixture(claimedNative).join('\n'), /native consumption/);

  const claimedValid = structuredClone(fixture);
  claimedValid.vectors[3].expected.contract_valid = true;
  assert.match(checkFixture(claimedValid).join('\n'), /expected contract_valid=true/);

  const claimedRejection = structuredClone(fixture);
  claimedRejection.vectors[1].expected.rejection = 'digest';
  assert.match(checkFixture(claimedRejection).join('\n'), /expected rejection=digest, got schema/);
});

test('native source gate is fail-closed and fixture status follows its exact level', () => {
  const report = inspectNativeConsumers(root);
  assert.ok(report.status === 'not_proven' || report.status === 'native_unit_consumers');
  assert.equal(report.checks.length, 2);
  assert.equal(report.status, buildFixture().native_consumption_status);
  assert.ok(nativeConsumerFailures(root).every((failure) => /ios|android/.test(failure)));
  assert.equal(NATIVE_CONSUMER_MARKER, 'MOBILE_AI_KEYBOARD_SHORTCUT_GOLDEN_CONSUMER_V1');
});

test('vector checker rejects expected digest and identity tampering', () => {
  const fixture = buildFixture();
  const digestExpectationTampered = structuredClone(fixture);
  digestExpectationTampered.vectors[0].expected.content_digest = `sha256:${'0'.repeat(64)}`;
  assert.match(checkFixture(digestExpectationTampered).join('\n'), /expected content_digest/);

  const identityTampered = structuredClone(fixture);
  identityTampered.vectors.reverse();
  assert.match(checkFixture(identityTampered).join('\n'), /vector order\/identity/);

  const shapeTampered = structuredClone(fixture);
  shapeTampered.vectors[0].expected.extra = 'ignored by an unsafe consumer';
  assert.match(checkFixture(shapeTampered).join('\n'), /expected keys are not exact/);
});
